# Generated by Django 4.2.19 on 2025-03-21 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('dataInicio', models.DateField(default=False)),
                ('dafaFim', models.DateField(default=False)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('entrega', models.CharField(choices=[('Retirar', 'Retirar'), ('Entrega', 'Entrega')], max_length=10)),
                ('cep', models.CharField(default=False, max_length=20)),
                ('cidade', models.CharField(default=False, max_length=20)),
                ('estado', models.CharField(default=False, max_length=20)),
                ('rua', models.CharField(default=False, max_length=100)),
                ('bairro', models.CharField(default=False, max_length=100)),
                ('numero', models.CharField(default=False, max_length=100)),
                ('pedido', models.CharField(choices=[('Pendente', 'Pendente'), ('Concluído', 'Concluído')], default='Pendente', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='ra',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('img1', models.CharField(max_length=100)),
                ('img2', models.CharField(max_length=100)),
                ('img3', models.CharField(max_length=100)),
                ('valor', models.IntegerField()),
                ('quantidade', models.IntegerField()),
                ('tipo', models.CharField(choices=[('Físico', 'Físico'), ('Virtual', 'Virtual')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('idCampanha', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='api.campanha')),
            ],
        ),
        migrations.CreateModel(
            name='ItensCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtdProduto', models.IntegerField()),
                ('idCompra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.compra')),
                ('idProduto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Desafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor', models.IntegerField()),
                ('dataInicio', models.DateField(default=False)),
                ('dafaFim', models.DateField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('idCampanha', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='api.campanha')),
            ],
        ),
    ]
