# Generated by Django 4.2.19 on 2025-04-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='imgPerfil',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
    ]
