# Generated by Django 4.2.19 on 2025-04-08 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_imgperfil_alter_produto_img1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='complemento',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='desafio',
            name='descricao',
            field=models.TextField(default=False),
        ),
    ]
