# Generated by Django 4.2.19 on 2025-03-26 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_imgperfil_customuser_saldo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campanha',
            old_name='dafaFim',
            new_name='dataFim',
        ),
        migrations.RenameField(
            model_name='desafio',
            old_name='dafaFim',
            new_name='dataFim',
        ),
    ]
