# Generated by Django 4.2.19 on 2025-04-09 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_compra_complemento_desafio_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desafio',
            name='idCampanha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.campanha'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='idCampanha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.campanha'),
        ),
    ]
