# Generated by Django 4.2.19 on 2025-04-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_desafio_idcampanha_alter_produto_idcampanha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desafio',
            name='dataFim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='desafio',
            name='dataInicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='desafio',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
