# Generated by Django 4.2.19 on 2025-04-15 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_desafio_datafim_alter_desafio_datainicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanha',
            name='predefinida',
            field=models.BooleanField(default=False),
        ),
    ]
