# Generated by Django 4.2.19 on 2025-04-23 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_campanha_predefinida'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pontuacao',
            field=models.IntegerField(default=0),
        ),
    ]
