# Generated by Django 4.2.20 on 2025-04-28 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customuser_pontuacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoSaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_anterior', models.IntegerField()),
                ('saldo_novo', models.IntegerField()),
                ('diferenca', models.IntegerField()),
                ('data_alteracao', models.DateTimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_saldo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_alteracao'],
            },
        ),
    ]
