# Generated by Django 4.2.19 on 2025-04-25 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customuser_pontuacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='primeiroAcesso',
            field=models.BooleanField(default=True),
        ),
    ]
