# Generated by Django 4.2.19 on 2025-04-30 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_customuser_primeiroacesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='dataCompra',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
